### ISSUE TITLE
Search function is not working in the market place

### ISSUE THREAD

**Issue by Alternating** [syscoin/blockmarket-desktop-public#98] opened 2017-05-16 20:43 UTC
New and old items i have posted I cannot search for.

Entering in bacon does not show me any results
entering in portal does not show me my portal gun for sale

**Comment by dwasyluk** [comment] 2017-05-17 03:44
Closing as duplicate of #103 which has more detail, pls continue chat there.

**Closed by dwasyluk** 2017-05-17 03:44 UTC
