### ISSUE TITLE
Blockmarket wallet 1.1.4 - Stuck on loading screen

### ISSUE THREAD

**Issue by MarkHusss** [syscoin/blockmarket-desktop-public#289] opened 2017-12-24 02:26 UTC
Just installed wallet 1.1.4. For an hour, been stuck on loading screen, cogs turning. I tried reinstalling; no effect.  I run win 10. I had 1.1.0 installed before, which did not have this problem.
edit: I also followed the steps here: http://www.syscoin.io/support/solutions/articles/31000137147-blockmarket-is-not-working-or-doesn-t-get-past-loading-screen-spinning-gears
no effect

**Comment by dwasyluk** [comment] 2018-01-10 04:25
Duplicate of #264.

**Closed by dwasyluk** 2018-01-10 04:25 UTC
