### ISSUE TITLE
Need a sanity check stage after clicking Buy Now

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#110] opened 2017-05-16 22:11 UTC
I just bought an orange 2 piece swimsuit that I really don't need. Had there been a sanity check popup  between clicking Buy Now and sending the transaction (maybe with order details, amounts etc like the Qt wallet), none of this would have happened and I'd still be a married man.

**Comment by sidhujag** [comment] 2017-05-17 00:51
Will need a call to backend which returns the tx unsigned to get full amount. 2.2 supports this.. so need to work this in with bm web

**Comment by dwasyluk** [comment] 2017-05-17 03:41
I think he means we just need a purchase confirmation step before firing the request to purchase. Makes sense for final imo, will try to get in beta3.

**Comment by dwasyluk** [comment] 2017-05-17 03:49
Closing as duplicate of #92.

**Comment by dwasyluk** [comment] 2017-05-18 01:41
This was closed by accident, reopenin.

**Comment by sidhujag** [comment] 2017-06-09 18:18
Implemented a confirmation before sending money, need to look at making it a bit cleaner at the code level but if it works we can port it over to any outgoing action.

**Comment by dwasyluk** [comment] 2017-06-10 02:41
I spoke with @jeroenvanwissen about the best UX here and might change the implementation before applying it to everything else, but you'll see that in b5.

**Closed** 2017-08-24 12:02 UTC
Labels: enhancement, highpriority, user experience improvement
