### ISSUE TITLE
Offer activates not showing up in dashboard syscoin tx list

### ISSUE THREAD

**Issue by sidhujag** [syscoin/blockmarket-desktop-public#79] opened 2017-05-16 18:31 UTC
for some reason offer activates (any maybe others?) not showing up (systx field is empty).. this is a core fix.

**Comment by dwasyluk** [comment] 2017-05-16 20:47
Closing as dupe of #97 because it has more info and screenshots.

**Closed by dwasyluk** 2017-05-16 20:47 UTC
