### ISSUE TITLE
Sending sys, posting, replies, anything that is an action out going

### ISSUE THREAD

**Issue by Alternating** [syscoin/blockmarket-desktop-public#92] opened 2017-05-16 20:35 UTC
Basically this needs a confirmation page so someone doesn't keep sending/posting/replying over and over and over and over again..

**Comment by dwasyluk** [comment] 2017-05-17 03:49
See #110 for another scenario.

**Comment by dwasyluk** [comment] 2017-05-18 01:39
Closing as dupe of #91, will include note there about #110.

**Closed by dwasyluk** 2017-05-18 01:39 UTC
Labels: enhancement, highpriority

**Comment by dwasyluk** [comment] 2017-05-18 01:41
Between #91 and #110 this case is covered.
