### ISSUE TITLE
Updating offers - Missing info

### ISSUE THREAD

**Issue by Alternating** [syscoin/blockmarket-desktop-public#88] opened 2017-05-16 20:12 UTC
When adding any update to a current offer you must edit the title. Simply clicking into the box and adding a space then deleting it alleviates the problem. You can then post your update. I noticed only the title field needs an edit in order to update the offer

**Comment by dwasyluk** [comment] 2017-05-18 01:38
Duplicate of #101

**Closed by dwasyluk** 2017-05-18 01:38 UTC
Labels: bug, highpriority
