### ISSUE TITLE
Blockmarket 1.0 - on loading it show 100%, but indeed it is not

### ISSUE THREAD

**Issue by locutus75** [syscoin/blockmarket-desktop-public#243] opened 2017-09-15 16:39 UTC
After loading the application is shows that "Recent Blocks" is green and 100%; infact, it is syncing, so it should not be green while the application starts.

**Comment by sidhujag** [comment] 2017-09-15 17:13
what block is it on when it shows 100%

**Comment by johnp1954** [comment] 2017-09-15 17:16
I have seen this shows 100% when not fully but nearly synced

**Comment by locutus75** [comment] 2017-09-15 19:38
it shows a block in the past at first loading, I can see that because the date is off

**Comment by locutus75** [comment] 2017-09-17 20:36
This issue is also present when I resume my computer from hibernation or sleep mode.

**Comment by johnp1954** [comment] 2017-09-20 16:24
Here is an example 
![image](https://user-images.githubusercontent.com/16462796/30655360-9b2bb790-9e28-11e7-86aa-9f884e749365.png)

**Comment by sidhujag** [comment] 2017-10-04 18:32
I see this issue have reproduced it and fixed for 1.02

**Comment by dwasyluk** [comment] 2017-11-18 22:00
Closing as duplicate of #255

**Closed by dwasyluk** 2017-11-18 22:00 UTC
Labels: ready for internal testing
