### ISSUE TITLE
Notifications show transactions from old wallet

### ISSUE THREAD

**Issue by sysmca** [syscoin/blockmarket-desktop-public#213] opened 2017-08-20 11:39 UTC
I created a brand new wallet and in the notifications area (bell icon) I saw transactions from my previous wallet.

Steps:

1. Create a wallet - perform some transactions
2. Close wallet
3. Delete the wallet.dat
4. Open wallet
5. Observe your transactions from the old wallet

(beta 5f)

**Comment by dwasyluk** [comment] 2017-09-01 00:25
We'll change how recent activity works to pertain only to your active session. Since it was prev storing actions from other sessions that was the cause of this bug.

**Comment by sidhujag** [comment] 2017-09-01 16:54
retest

**Comment by dwasyluk** [comment] 2017-11-18 22:13
Closing as its from beta times.

**Closed by dwasyluk** 2017-11-18 22:13 UTC
Labels: needs retest
