### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by urkovs** [syscoin/blockmarket-desktop-public#264] opened 2017-11-06 17:18 UTC
I have Mac OS Sierra on a Macbook Air. I am trying to use the Blockmarket v1.1.0. When I open it, I see the startup screen with the two gears turning around, and text displayed which says "Blockmarket Desktop Loading". However, it goes nowhere from that display. Nothing ever loads.

Is there a fix for this or is it a known bug?
![screen shot 2017-11-06 at 9 18 28 am](https://user-images.githubusercontent.com/31389454/32454239-7de45e42-c2d3-11e7-8f77-3b550cc0297a.png)

**Comment by johnp1954** [comment] 2017-11-06 17:22
have you run the Beta Desktop before

**Comment by urkovs** [comment] 2017-11-06 17:24
I just downloaded it, tried to open it, got stuck on this screen. Then I closed it and reopened it. Same thing.

**Comment by johnp1954** [comment] 2017-11-06 17:25
Sorry you didnt answer the question can you go to the #help channel in Slack

**Comment by willyko** [comment] 2017-11-14 20:52
This is 1.1.0, could you try with Blockmarket 1.1.1?  
[https://github.com/syscoin/blockmarket-desktop-public/releases/tag/1.1.1](url)

**Comment by dwasyluk** [comment] 2017-11-18 21:16
This has been reported by several people, it seems to be isolated to OSX users at the moment.

**Comment by CharlieSmith** [comment] 2017-11-19 01:34
I'm having same issue on win7, I closed the program then went to open it again and possibly the deamon or cli process was still running.

**Comment by peteralexander25** [comment] 2017-11-28 01:00
this has hjappened to me on windows 10 never loads. any help out there

**Comment by romeshomey** [comment] 2017-12-17 22:54
Windows 10 here, I'm currently stuck on loading screen, followed the above post.  Ended up deleting blockchain and all files from %appdata%/Syscoin and %appdata%/Blockmarket and letting it create a new wallet.  Id moved my coins and deleted the backups, guess I should have made a copy like above and overwrote the new wallet with the copy, idk, still stuck...

I did notice that syscoind wants to stay running even when you close the Blockmarket client which also prevents you from deleting or moving files in the folders, thats the first issue I ran into as everytime I'd delete the wallet.dat it would continue to recreate a new one over and over until I'd realized the syscoind wasn't closing.

Bah....

**Comment by romeshomey** [comment] 2017-12-17 23:00
It finally opened.  Guess I had to let it sit there on that screen for a while.

**Comment by kitovyj** [comment] 2018-01-08 14:40
I'm experiencing the issue now, win64

**Comment by dwasyluk** [comment] 2018-02-06 02:18
I have steps to reproduce this from a known-working state but need to test and verify, this may only be one variant of the causes:

1. Load blockmarket, it should load.
2. Close blockmarket properly.
3. Using the filesystem change wallet.dat in a way that will force a rescan
4. Restart blockmarket - it should hang on the loading screen

The issue / part of the issue seems to be when BM runs syscoind in a state that introduces anything other than a standard load-up, it seems the syscoind process can become detached from the BM process. I ran into this myself and only noticed when I fell back to QT after quitting BM and it complained syscoind was still running. Sure enough:

<img width="800" alt="screen shot 2018-02-05 at 9 15 32 pm" src="https://user-images.githubusercontent.com/987186/35838538-c1967bec-0ab9-11e8-8dff-c086f8eac6d4.png">

I suspect a similar but inverted situation may occur when BM is left running for a long time (syscoind will quit, resulting in 500s from the BM side).

**Comment by romeshomey** [comment] 2018-02-07 00:49
I'm still dealing with this issue.  I can't even remember the last time I actually got the Blockmarket Desktop to open.  Downloaded update after reading this update, installed, executed, and..... stuck on loading screen as usual.

**Comment by Keyare** [comment] 2018-02-07 00:52
http://www.syscoin.io/support/solutions/articles/31000137147-blockmarket-is-not-working-or-doesn-t-get-past-loading-screen-spinning-gears

**Comment by romeshomey** [comment] 2018-02-07 01:33
Ok, after following the steps in the above link, it worked and opened, however, the only wallet file i was able to find my my old data directory was a wallet(stringofrandonnumbers).bak

Like my wallet.dat had been overwritten by the above file.

**Comment by romeshomey** [comment] 2018-02-07 01:58
Something not right.  I've tried several syscoin wallet.dat backups and can't get any of them to open in Blockmarket,  After placing them in the new syscoin data directory and executing Blockmarket, wallet doesn't load and after closing the wallet.dat backups remain unchanged with unchanged last modified date still being in 2016.

**Comment by romeshomey** [comment] 2018-02-07 02:08
I'm just going to assume my old wallet got corrupted somehow and fortunately I haven't got any coins on there anymore so its no big deal, however I'd be disappointed if I'd still had a balance on the wallet.

**Comment by romeshomey** [comment] 2018-02-07 02:35
Still looking for my syscoins.  I can't get the wallet I'd moved them to to load.  Missing 10,187 coins somewhere.

**Comment by doublesharp** [comment] 2018-02-23 02:19
If you don't have another `syscoind` process already running you likely need to reindex. 

A temporary workaround for this issue on OSX is to run the following commands from a Terminal window. It will trigger a reindex of the internal database which might be slow. Balances/Aliases/etc will not be accurate until the blocks have finished syncing.

```
# Location of the Blockmarket Desktop syscoin.conf, may be different from QT or syscoind
SYSCOIN_CONF=~/Library/Application\ Support/Blockmarket/syscoin.conf

# Use the same binaries as the desktop client
cd /Applications/Blockmarket.app/Contents/Resources/bin/darwin/
# Reindex using the appropriate conf file, make sure to include & at the end
./syscoind --conf=$SYSCOIN_CONF -reindex &
# Gracefully shutdown syscoind using the cli
./syscoin-cli --conf=$SYSCOIN_CONF stop
```

You should then be able to open Blockmarket.app successfully, again note that it will take some time to resync.

**Comment by doublesharp** [comment] 2018-02-23 02:43
@dwasyluk the failure to load when another `syscoind` is a similar but unrelated issue. You need to stop it with the cli via `syscoin-cli stop` or if it is a rogue process that cannot be stopped `killall syscoind`.

**Comment by sebastien1234** [comment] 2018-03-16 17:08
Tested on Windows 10, no problem with being stuck on loading screen.

**Closed** 2018-03-16 22:37 UTC
Labels: bug, highpriority, ready for internal testing, reviewed by team

**Comment by r3lik** [comment] 2018-05-03 21:33
having the same issues on OSX with Blockmarket v1.0.1
