### ISSUE TITLE
No accepted currencies

### ISSUE THREAD

**Issue by AlexandrZT** [syscoin/blockmarket-desktop-public#266] opened 2017-11-12 15:53 UTC
During post of new item for sale Accepted currencies box is missing.
Blockmarket 1.1.1

**Comment by willyko** [comment] 2017-11-14 20:48
Accepted currencies will come in Blockmarket 1.2 when we implement integrated payment processors

**Comment by dwasyluk** [comment] 2017-11-18 21:12
Closing as duplicate of #40

**Closed by dwasyluk** 2017-11-18 21:12 UTC
