### ISSUE TITLE
Sending to alias you own does not show in txlist

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#44] opened 2017-05-10 19:09 UTC
Send some sys to an Alias I own no record of it happening on transactions

**Comment by sebastien1234** [comment] 2017-05-11 00:52
is that within the same wallet @johnp1954 ? does a transaction appear after you close and reopen the wallet?

**Comment by johnp1954** [comment] 2017-05-11 08:58
Yes within the same wallet and it does not appear after opening and closing

John


On 11 May 2017, at 01:52, sebastien1234 <notifications@github.com<mailto:notifications@github.com>> wrote:


is that within the same wallet @johnp1954<https://github.com/johnp1954> ? does a transaction appear after you close and reopen the wallet?

**Comment by dwasyluk** [comment] 2017-05-11 19:36
@johnp1954 does this only happen when you send to an alias? ie: if you send to a SYS address, close and reopen BM b1 you see the tx- but do same when sending to alias and you _**do not**_ see it? Just trying to narrow scope, thanks!

**Comment by johnp1954** [comment] 2017-05-11 22:01
This ONLY happens when you send to an alias you own ie send to yourself

**Comment by dwasyluk** [comment] 2017-05-11 22:02
Perfect thanks for the additional info, very helpful 👍

**Comment by sidhujag** [comment] 2017-05-12 17:34
retest in beta2

**Comment by johnp1954** [comment] 2017-05-16 20:11
Not Fixed

**Comment by sebastien1234** [comment] 2017-05-17 04:09
confirmed not fixed @dwasyluk sending to self does not generate a transaction and does not change the balance of said alias

**Comment by johnp1954** [comment] 2017-08-19 14:33
Not fixed changes alias balance but no TX is shown even after closing and opening

**Comment by willyko** [comment] 2017-08-23 20:57
Confirm that TX is not shown in recent transaction table.  SYS does get moved to the alias and debug mode shows a valid txid as "send to address response".  
@sidhujag could you comment on this?

**Comment by sidhujag** [comment] 2017-08-23 21:06
If sys does get moved this its fine, retest in bm web

**Comment by johnp1954** [comment] 2017-11-02 14:35
Is this fixed in BM 1.1

**Comment by sidhujag** [comment] 2017-11-02 14:38
No

**Comment by dwasyluk** [comment] 2017-11-18 22:34
closing as duplicate of #259

**Closed by dwasyluk** 2017-11-18 22:34 UTC
Labels: bug, retest in bm web
