### ISSUE TITLE
Password Problems

### ISSUE THREAD

**Issue by joeyb333** [syscoin/blockmarket-desktop-public#328] opened 2018-02-17 05:43 UTC
I am not able to unlock my wallet. When I first downloaded and funded my wallet in Nov. 2017, I used a PW with a *. Now I am trying to use the platform but cannot unlock my wallet. I see my funds. I downloaded the 1.2 version and still same problem. Funds are there, but I cannot use the platform. Please help. Thanks!

**Comment by willyko** [comment] 2018-02-17 08:33
The work around right now is to download 2.1.6 QT wallet, and use that to unlock/change password.

**Comment by willyko** [comment] 2018-02-17 08:41
duplicate of #313

**Closed by willyko** 2018-02-17 08:41 UTC
