### ISSUE TITLE
Balance does not show

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#33] opened 2017-05-10 18:27 UTC
Balance does not show until restart wallet

**Comment by dwasyluk** [comment] 2017-05-11 19:49
@johnp1954 are you referring to top right balance or home balance or both? I think you may have closed the wallet prematurely if it was home balance. When you open wallet now what happens- do you see home balance and top right balance as same or is this a duplicate of #47 ?

**Comment by johnp1954** [comment] 2017-05-11 22:05
Yes this is the same as #47

**Comment by dwasyluk** [comment] 2017-05-11 22:13
Thanks for the confirmation, going to close this as duplicate as I'd planned on working on #47 later tonight, should be in beta2 👍 .

Closing as duplicate of #47

**Closed by dwasyluk** 2017-05-11 22:13 UTC

**Comment by johnp1954** [comment] 2017-05-16 20:09
Fixed
