### ISSUE TITLE
Marketplace results page auto-loads wrong items after viewing subcategories 

### ISSUE THREAD

**Issue by bstr156** [syscoin/blockmarket-desktop-public#287] opened 2017-12-22 00:59 UTC
Using BMD 1.1.4

To replicate the issue, do the following:

1. Navigate into a category that has subcategories (e.g. Auto/Vehicle) and let it load.  For extra measure, go into a subcategory for which there aren't any listings (e.g. RVs/Campers).
2. Immediately return to the main categories and select a different category (e.g. Alternatives), let it load, then wait a moment and keep watching...   

At first the page loads the proper items for the selected category, but then immediately clears and loads items from categories that do not belong.  

This behavior seems to be triggered specifically by viewing categories that have subcategories.  It also seems to suddenly correct after viewing a few different main categories, until once again going to one with subcategories which manifests the issue again.

**Comment by dwasyluk** [comment] 2018-01-10 04:21
This is caused by a race between category requests. What needs to happen is the prev request needs to be cancelled / better managed. Another option is disabling the category nav while a request is in flight and re-enabling it when completed.

**Comment by dwasyluk** [comment] 2018-02-02 16:10
Fixed by @sschepis

**Closed by dwasyluk** 2018-02-02 16:10 UTC
Labels: reviewed by team
