### ISSUE TITLE
Blockmarket desktop not syncing?

### ISSUE THREAD

**Issue by stepwi4** [syscoin/blockmarket-desktop-public#293] opened 2018-01-05 19:08 UTC
Downloaded Blockmarket desktop for windows but just shows "No blocks found" under Recent Blocks. I'm thinking it's not syncing. Any ideas?

**Comment by johnp1954** [comment] 2018-01-05 19:11
Please go to the help channel and ask

**Comment by stepwi4** [comment] 2018-01-05 19:22
What help channel?

**Comment by stepwi4** [comment] 2018-01-05 19:26
I'm new to all this so I'm trying to figure it all out.

**Comment by johnp1954** [comment] 2018-01-05 19:28
In Slack you are a member look at the channels on the left

**Comment by stepwi4** [comment] 2018-01-05 19:30
I've heard of Slack but not sure what it is. You say I am a member?

**Comment by johnp1954** [comment] 2018-01-05 19:31
Can you give me your Email and I will invite you then we can sort this

**Comment by stepwi4** [comment] 2018-01-05 19:31
stepwi4@gmail.com

**Comment by johnp1954** [comment] 2018-01-05 19:33
Sent just ask for johnp when you join

**Comment by solidcloudio** [comment] 2018-01-05 20:35
Can you add me to slack also
zapbbx@gmail.com

**Comment by Sporadic92** [comment] 2018-01-06 03:16
Add me to slack as weel Jakelawlor92@gmail.com

**Comment by cobbju** [comment] 2018-01-06 08:33
Same issue, can you add me to slack as well kratosebay@gmail.com

**Comment by johnp1954** [comment] 2018-01-06 10:10
Invites sent

**Comment by flynnp3** [comment] 2018-01-06 13:23
can you email me too, flynnp9@tcd.ie , sent 90 coins to wallet last night and no sync bar

**Comment by dwasyluk** [comment] 2018-01-10 04:30
Duplicate of #292 - caused by our sys seeds being down. Has since been fixed, please comment if still having issues.

**Closed by dwasyluk** 2018-01-10 04:30 UTC

**Comment by kzrt66** [comment] 2018-01-16 06:54
Hi all.
I am new to this space, and not tech savvy. Please help.

I downloaded Blockmarket and synced yesterday. When I opened it, it had to be synced all over again.
Is it a normal procedure, or did I make a mistake? (As a matter of fact, when I tried to open, a error message window popped up.)

Thank you very much for your help.

**Comment by kzrt66** [comment] 2018-01-16 07:15
Hi all. 
I am new to this space and not tech savvy at all.  Your help is most appreciated.

I installed Blockmarket yesterday, and syncing completed after a few hours.
When I opened it today, I only found 0% sync, and had to wait for the syncing to complete again. It appears syncing is much faster than yesterday.

Q1. Do I have to sync from the beginning every time I open Blockmarket?
Q2. There was an error message window when I opened Blockmarket although I was able to go to Home/Dashboard. Do I need to fix them all? And how?

Thank you very much!
