### ISSUE TITLE
send message to seller from offer page without directly buying offer

### ISSUE THREAD

**Issue by phbart** [syscoin/blockmarket-desktop-public#142] opened 2017-06-11 09:52 UTC
If I have interest in an offer but have some questions regarding it before buying, It would be nice to be able to send a note to seller from the offer itself (like is possible now) and submit it without directly buying it. 

Now I can only sent a note to seller if I buy the object or I have to go to messages first.

**Comment by dwasyluk** [comment] 2017-11-18 22:24
Closing as duplicate of #237

**Closed by dwasyluk** 2017-11-18 22:24 UTC
Labels: enhancement
