### ISSUE TITLE
Transation not showing up in "Transaction list"

### ISSUE THREAD

**Issue by cryptme00** [syscoin/blockmarket-desktop-public#242] opened 2017-09-15 11:50 UTC
I've upgraded my 2.1.4 to Blockmarket 1.0.0, overall balance is OK. I've transferred today some coins to the old address imported from 2.1.4, balace shows up correctly in "All accounts", but in "Transaction list" I don't see those transactions.

**Comment by dwasyluk** [comment] 2017-11-18 22:01
Closing as duplicate of #259

**Closed by dwasyluk** 2017-11-18 22:01 UTC
