### ISSUE TITLE
Blockmarket Desktop 1.0.1 will not load on Mac OS Sierra. 

### ISSUE THREAD

**Issue by ricardopayen** [syscoin/blockmarket-desktop-public#257] opened 2017-10-29 19:28 UTC
I have been getting a perpetual spinning cog for the past few days. Ever since purchasing my first amount of syscoin and transferring it into my Wallet :(. Have not been able to confirm if the transaction went all the way through. I have tried reinstalling.

**Comment by dwasyluk** [comment] 2017-11-18 21:50
Duplicate of #264

**Closed by dwasyluk** 2017-11-18 21:50 UTC
