### ISSUE TITLE
Add Back Button

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#72] opened 2017-05-16 01:50 UTC
There are a number of places where navigation becomes stuck because there's no way to go back to the previously viewed screen, such as when editing or finished editing or posting a new offer.

**Comment by dwasyluk** [comment] 2017-05-17 03:54
Breadcrumb should cover this, also closing as dupe of #111 lets centralize convo there.

**Closed by dwasyluk** 2017-05-17 03:54 UTC
Labels: enhancement
