### ISSUE TITLE
Alias Creation

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#334] opened 2018-03-06 20:01 UTC
When you create an Alias and change the expiring date to a date far into the future the cost can be extremely high. Can you show the estimated cost of an Alias when the date is changed, or an acceptance dialog stating the rough cost when pressing OK

**Comment by doublesharp** [comment] 2018-03-06 21:09
- Enforcing min/max dates within the UI, set to 1 year and 5 years.
- Showing the max alias fee (based on max transaction size in bytes), will be updated with a more accurate amount in core3.0

**Comment by dwasyluk** [comment] 2018-03-13 20:47
The actual root cause here is likely the polling mechanism that starts when you `aliasnew`. There is an async process for writing the alias public data may be the root cause here. If that polling mechanism gets tripped up by user actions (within BM or by closing/opening BM) the offchain data won't be written to the mongo DB, but the read side of the BM:DT experience is asynchronous to this so it will encounter an error when reading from the offchain DB.

**Closed** 2018-03-16 22:37 UTC
Labels: enhancement, reviewed by team, user experience improvement
