### ISSUE TITLE
ERRCODE 1073 - Payment option not found

### ISSUE THREAD

**Issue by timelessdesign** [syscoin/blockmarket-desktop-public#179] opened 2017-07-08 21:05 UTC
"ERRCODE 1073 - User selected payment option not found in list of accepted offer payment options."
Could not purchase item even though the price in the offer was in SYS and I have enough SYS in balance (did not see where I could even choose another payment option to buy the offer).

<img width="1440" alt="screen shot 2017-07-08 at 23 53 11" src="https://user-images.githubusercontent.com/30006325/27989087-26830420-643a-11e7-9c3b-aaf2b24abf2d.png">

**Comment by sidhujag** [comment] 2017-07-10 16:49
This one only accepts BTC, just need to display it as the accepted payment option, its priced in SYS.

**Comment by sidhujag** [comment] 2017-07-10 16:55
retest in b6(rc1)

**Comment by willyko** [comment] 2017-08-24 00:19
@sidhujag tested this; issue not fixed.  It does show that only BTC is accepted...so there's no way of purchasing it?  what's the expected process/result anyway?

**Comment by sidhujag** [comment] 2017-08-24 00:21
btc payments will come in bm web

**Comment by dwasyluk** [comment] 2017-11-18 21:11
Closing as duplicate of #40

**Closed by dwasyluk** 2017-11-18 21:11 UTC
Labels: retest in bm web
