### ISSUE TITLE
BlockMarket error Screen shot provided

### ISSUE THREAD

**Issue by peekay69** [syscoin/blockmarket-desktop-public#125] opened 2017-05-18 23:56 UTC
![cbbmbmbmture](https://cloud.githubusercontent.com/assets/28594481/26227983/eb98cbf0-3c03-11e7-8324-8a28859f1394.PNG)

**Comment by dwasyluk** [comment] 2017-05-23 07:15
How long had wallet been running before this error?

**Comment by dwasyluk** [comment] 2017-05-23 07:15
possibly related to #120

**Comment by dwasyluk** [comment] 2017-05-29 21:33
Closing as duplicate of #120.

**Closed by dwasyluk** 2017-05-29 21:33 UTC
Labels: bug
