### ISSUE TITLE
Sending to a local Alias you own does not show confirm or update balances.

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#163] opened 2017-06-28 18:31 UTC
If you send to an alias you own locally, it will not show confirmed and will not change your balances until you restart BM.
Once restarted balances be accurate but the TX does not show up in your TX list.

**Comment by sidhujag** [comment] 2017-07-12 20:10
retry in bm web

**Comment by willyko** [comment] 2017-08-24 01:12
duplicate of #44

**Closed by willyko** 2017-08-24 01:12 UTC
